#let title = "Title"
#let program = "Study"
#let supervisor = "Supervisor name"
#let author = "Your Name"
#let university = "University"
#let description = "Description"
#let logo_path = "/figures/0_titlepage/logo_example.jpg"
#let bib_path = "/references.bib"
#let submissionDate = datetime(day: 1, month: 1, year: 2025)