name: Build and release paper

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_release_paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install required fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://mirrors.ctan.org/fonts/newcomputermodern.zip
          unzip newcomputermodern.zip
          sudo mkdir -p /usr/local/share/fonts/newcomputermodern
          sudo cp newcomputermodern/otf/* /usr/local/share/fonts/newcomputermodern/
          fc-cache -f -v
          rm -rf newcomputermodern*

      - name: Create initial tag
        run: |
          if [ -z "$(git tag -l 'v*')" ]; then
            git tag v0.0.0
          fi

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'patch'

      - uses: typst-community/setup-typst@v4

      - name: Compile documents
        run: |
          typst compile paper.typ paper.pdf

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Version ${{ steps.bump.outputs.new_tag }}
          draft: false
          prerelease: false
          files: |
            paper.pdf
